name: Deploy documentation (MkDocs)

on:
  push:
    branches: [ 'fix/documentation' ]
    paths:
      - 'mkdocs/**'
      - 'docs/**'
      - 'src/**'
      - 'pyproject.toml'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/python_build
        with:
          python-version: '3.11'
          tags: "[cicd,docs]"

      - run: python --version

      - run: mkdocs build -f mkdocs.yml -d site

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
