name: Lint & Type Check

on:
  push:
    branches: [ "fix/documentation" ]
  pull_request:
    branches: [ "fix/documentation" ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package + dev extras
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run Black (check only)
        run: |
          black . --check --diff

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Run Mypy
        run: |
          mypy $(git ls-files '*.py')
